CREATE TABLE RECORD(
	ID INT AUTO_INCREMENT,
	ARTIST VARCHAR(255),
	RECORD_NAME VARCHAR(255),
	RECORD_DESC VARCHAR(2000),
	GENRE VARCHAR(255), 
	RECORD_CONDITION VARCHAR(255),
	PRICE DOUBLE,
	RELEASE_YEAR INT
);
